# Generated by Django 2.2.1 on 2019-05-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='topic_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
