# Generated by Django 2.2.1 on 2019-05-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190526_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_comments',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
