# Generated by Django 2.1.7 on 2019-04-29 10:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_category', models.CharField(max_length=30)),
                ('topic_title', models.CharField(max_length=200)),
                ('topic_image', models.ImageField(upload_to='')),
                ('datetime', models.DateTimeField(default=datetime.datetime(2019, 4, 29, 12, 37, 20, 91847), verbose_name='date published')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TopicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_summary', models.CharField(max_length=200)),
                ('topic_comments', models.CharField(max_length=200)),
                ('comment_published', models.DateTimeField(default=datetime.datetime(2019, 4, 29, 12, 37, 20, 91847), verbose_name='date published')),
                ('topic_category_key', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TopicCategory', verbose_name='Categories')),
            ],
            options={
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
