# Generated by Django 2.1.7 on 2019-04-29 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190429_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicinformation',
            name='topic_category_key',
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='topic_category_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TopicInformation', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 14, 56, 18, 137529), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 4, 29, 14, 56, 18, 136494), verbose_name='date published'),
        ),
    ]
