# Generated by Django 2.1.7 on 2019-05-02 13:04

import datetime
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190430_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40, verbose_name=django.contrib.auth.models.User)),
            ],
            options={
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 3, 59, 653999), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 3, 59, 653002), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='topiccategory',
            name='profile_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Profile', verbose_name='Profiles'),
        ),
    ]
