# Generated by Django 2.1.7 on 2019-05-02 13:13

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190502_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccategory',
            name='profile_key',
        ),
        migrations.AddField(
            model_name='topicinformation',
            name='user',
            field=models.CharField(default=1, max_length=40, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 13, 37, 187567), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 13, 37, 187567), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
