# Generated by Django 2.1.7 on 2019-05-02 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190502_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicinformation',
            name='user_profile',
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 37, 14, 899401), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 15, 37, 14, 898404), verbose_name='date published'),
        ),
    ]
