# Generated by Django 2.1.7 on 2019-05-03 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190503_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 4, 40, 877858), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 4, 40, 876861), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='user_comments',
            field=models.TextField(max_length=250),
        ),
    ]
