# Generated by Django 2.1.7 on 2019-05-03 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0037_auto_20190503_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 25, 41, 108469), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 25, 41, 109466), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 25, 41, 108469), verbose_name='date published'),
        ),
    ]
