# Generated by Django 2.1.7 on 2019-05-03 12:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20190503_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topiccategory',
            name='topic_category_key',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='topic_inf_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TopicInformation', verbose_name='Topics'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 53, 7, 105132), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 53, 7, 106130), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topicinformation',
            name='topic_category_key',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.TopicCategory', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 14, 53, 7, 106130), verbose_name='date published'),
        ),
    ]
