# Generated by Django 2.1.7 on 2019-05-03 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20190503_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 38, 23, 383254), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='comment_published',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 17, 38, 23, 385248), verbose_name='date published'),
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='topic_category_key',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='topic_category_key',
            field=models.ManyToManyField(to='main.TopicCategory'),
        ),
    ]
