# Generated by Django 2.1.7 on 2019-05-04 11:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_auto_20190503_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='comment_published',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 13, 20, 5, 26134), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 13, 20, 5, 25137), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
