# Generated by Django 2.1.7 on 2019-05-04 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20190504_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='datetime',
        ),
        migrations.AddField(
            model_name='usercomments',
            name='datetimeUser',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 13, 20, 55, 481080), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 4, 13, 20, 55, 480128), verbose_name='date published'),
        ),
    ]
