# Generated by Django 2.2.1 on 2019-05-18 17:07

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20190518_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 19, 7, 41, 213308), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='author',
            field=models.OneToOneField(on_delete=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='datetimeUser',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 19, 7, 41, 214306), verbose_name='date published'),
        ),
    ]
