# Generated by Django 2.1.7 on 2019-05-18 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20190518_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomments',
            name='comment_minus',
            field=models.CharField(default=None, max_length=222),
        ),
        migrations.AddField(
            model_name='usercomments',
            name='comment_plus',
            field=models.CharField(default=None, max_length=222),
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 20, 48, 13, 967585), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='datetimeUser',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 20, 48, 13, 968582), verbose_name='date published'),
        ),
    ]
