# Generated by Django 2.1.7 on 2019-05-18 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20190518_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercomments',
            name='comment_minus',
        ),
        migrations.RemoveField(
            model_name='usercomments',
            name='comment_plus',
        ),
        migrations.AlterField(
            model_name='topiccategory',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 20, 55, 10, 829366), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='usercomments',
            name='datetimeUser',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 18, 20, 55, 10, 830364), verbose_name='date published'),
        ),
    ]
