# Generated by Django 2.1.7 on 2019-05-21 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0100_auto_20190521_1819'),
        ('main', '0066_auto_20190508_1203'),
    ]

    operations = [
    ]
